
title: utopianism
email: oopsuto@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://oopsgogo.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  utopianism

# Build settings
markdown: kramdown

# theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

plugins:
  - jekyll-paginate
  - jekyll-toc
exclude:
  - Gemfile
  - Gemfile.lock

search: true

paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Site Author
author:
  name             : utopianism # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/miaomiao.jpg"
  bio              : "Thinking and writting."
  location         : "Guangzhou, CN"
  email            : oopsuto@gmail.com
  home             : "http://oopsgogo.com"
  github           : "utopianism"


# Reading Files
include:
  - .htaccess
  - _pages
  - "_posts/**/*.gif"
  - "/_posts/**/*.gif"
  - "/_posts/*.png"
  - "_posts/**/*.gif"
  - "_posts/*.png"
  - "**/*.gif"
  - "**/*.png"
#  - "_posts\**\*.gif"
#  - "_posts\*.png"
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false




category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      toc: true
      toc_label: " outline"
      toc_icon: "file-alt"
      share: true
      related: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
